# Generated by Django 5.2.7 on 2025-10-26 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('byline', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('homepage', models.URLField(blank=True)),
                ('rss', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('PERSON', 'PERSON'), ('ORG', 'ORG'), ('GPE', 'GPE'), ('EVENT', 'EVENT'), ('WORK', 'WORK'), ('OTHER', 'OTHER')], default='OTHER', max_length=12)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('to_read', 'to_read'), ('reading', 'reading'), ('read', 'read'), ('archived', 'archived')], db_index=True, default='to_read', max_length=16)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='api.source'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='api.tag'),
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ref', 'ref'), ('citation', 'citation'), ('update', 'update'), ('duplicate', 'duplicate'), ('same_story', 'same_story')], default='same_story', max_length=16)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_links', to='api.article')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_links', to='api.article')),
            ],
            options={
                'unique_together': {('src', 'dst', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='ArticleEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('salience', models.FloatField(default=0.0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_entities', to='api.article')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='api.entity')),
            ],
            options={
                'unique_together': {('article', 'entity')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='api_article_publish_6257ff_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='api_article_title_b34fa9_idx'),
        ),
    ]
