name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format